// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

/*
Package grpcapi is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	GrpcRequest
	GrpcResponse
*/
package grpcapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GrpcRequest struct {
	Input string `protobuf:"bytes,1,opt,name=input" json:"input,omitempty"`
}

func (m *GrpcRequest) Reset()                    { *m = GrpcRequest{} }
func (m *GrpcRequest) String() string            { return proto.CompactTextString(m) }
func (*GrpcRequest) ProtoMessage()               {}
func (*GrpcRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GrpcRequest) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

type GrpcResponse struct {
	Response string `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
}

func (m *GrpcResponse) Reset()                    { *m = GrpcResponse{} }
func (m *GrpcResponse) String() string            { return proto.CompactTextString(m) }
func (*GrpcResponse) ProtoMessage()               {}
func (*GrpcResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GrpcResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func init() {
	proto.RegisterType((*GrpcRequest)(nil), "grpcapi.GrpcRequest")
	proto.RegisterType((*GrpcResponse)(nil), "grpcapi.GrpcResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GrpcService service

type GrpcServiceClient interface {
	GrpcService(ctx context.Context, in *GrpcRequest, opts ...grpc.CallOption) (*GrpcResponse, error)
}

type grpcServiceClient struct {
	cc *grpc.ClientConn
}

func NewGrpcServiceClient(cc *grpc.ClientConn) GrpcServiceClient {
	return &grpcServiceClient{cc}
}

func (c *grpcServiceClient) GrpcService(ctx context.Context, in *GrpcRequest, opts ...grpc.CallOption) (*GrpcResponse, error) {
	out := new(GrpcResponse)
	err := grpc.Invoke(ctx, "/grpcapi.GrpcService/grpcService", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GrpcService service

type GrpcServiceServer interface {
	GrpcService(context.Context, *GrpcRequest) (*GrpcResponse, error)
}

func RegisterGrpcServiceServer(s *grpc.Server, srv GrpcServiceServer) {
	s.RegisterService(&_GrpcService_serviceDesc, srv)
}

func _GrpcService_GrpcService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServiceServer).GrpcService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.GrpcService/GrpcService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServiceServer).GrpcService(ctx, req.(*GrpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GrpcService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcapi.GrpcService",
	HandlerType: (*GrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "grpcService",
			Handler:    _GrpcService_GrpcService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0x2f, 0x2a, 0x48, 0x4e,
	0x2c, 0xc8, 0x54, 0x52, 0xe6, 0xe2, 0x76, 0x2f, 0x2a, 0x48, 0x0e, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d,
	0x2e, 0x11, 0x12, 0xe1, 0x62, 0xcd, 0xcc, 0x2b, 0x28, 0x2d, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0,
	0x0c, 0x82, 0x70, 0x94, 0xb4, 0xb8, 0x78, 0x20, 0x8a, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85,
	0xa4, 0xb8, 0x38, 0x8a, 0xa0, 0x6c, 0xa8, 0x42, 0x38, 0xdf, 0xc8, 0x1b, 0x62, 0x60, 0x70, 0x6a,
	0x51, 0x59, 0x66, 0x72, 0xaa, 0x90, 0x0d, 0x17, 0x77, 0x3a, 0x12, 0x57, 0x44, 0x0f, 0x6a, 0xb1,
	0x1e, 0x92, 0xad, 0x52, 0xa2, 0x68, 0xa2, 0x10, 0xa3, 0x94, 0x18, 0x92, 0xd8, 0xc0, 0xae, 0x35,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x2d, 0x11, 0x34, 0x26, 0xbe, 0x00, 0x00, 0x00,
}
